# Add the Forwarded header syntax
include includes/proxy-add-forwarded.conf;

log_format nirdclub-vhost-41 'date=\"$date_local\" vhost=\"$host\" sip=\"$server_addr\" port=\"$server_port\" proto=\"$server_protocol\" method=\"$request_method\" url=\"$uri\" rcode=\"$status\" rsize=\"$bytes_sent\" rtime=\"$request_time\" ua=\"$http_user_agent\" forwarded=\"$proxy_add_forwarded\"';

server {
    server_name dev.splitsp.lat;

    include includes/standard-http.conf;
    include includes/blockips.conf;
}

server {
    server_name dev.splitsp.lat;
    access_log  /var/log/nginx/vhost_nginx_access.log nirdclub-vhost-41;

    ssl_certificate /etc/letsencrypt/live/dev.splitsp.lat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.splitsp.lat/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/dev.splitsp.lat/chain.pem;

    location / {
        proxy_pass http://127.0.0.1:41081;
        add_header X-Clacks-Overhead "GNU Terry Pratchett";
        add_header X-via "birdland-cdn/splitsp-lat/8.29.23";
        include includes/location-includes.conf;
    }

    include includes/blockips.conf;
    include includes/letsencrypt.conf;
    include includes/ssl.conf;
    include includes/standard-ssl.conf;
}
