all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
  children:
    dev:
      vars:
        config_env: dev
      hosts:
        host78.nird.club:
          deploy_dir: /var/www/dev/splitsp-lat-web
    prod:
      vars:
        config_env: prod
      hosts:
        host74.nird.club:
          deploy_dir: /var/www/prod/splitsp-lat-web
