Listen 41080

<VirtualHost 0.0.0.0:41080>
    ServerName dev.splitsp.lat
    ServerAdmin webmaster@nird.club

    DocumentRoot "/var/www/prod/splitsp-lat-web/html"
    ErrorLog /var/log/apache2/vhost_httpd_error.log
    CustomLog /var/log/apache2/vhost_httpd_access.log nird-club
    ErrorDocument 404 /error.php

    <FilesMatch \.php$>
        SetHandler proxy:fcgi://php-fpm
    </FilesMatch>

    <Directory /var/www/prod/splitsp-lat-web/html>
        AllowOverride All
        Order allow,deny
        Allow from 127.0.0.1
        Options Includes Indexes FollowSymLinks MultiViews ExecCGI
        XBitHack on
        Require all granted
        DirectoryIndex index.php index.html
    </Directory>

</VirtualHost>
